version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: playwallet_db_v2
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pgdata_v2:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: playwallet_app_v2
    restart: unless-stopped
    ports:
      - "127.0.0.1:8001:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  topup:
    build: .
    container_name: playwallet_topup_v2
    restart: unless-stopped
    command: ["python", "app/auto_topup.py"]
    depends_on:
      app:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./logs:/app/logs

volumes:
  pgdata_v2:
